import type { PluginWidget } from "../types/plugin";

export const corePlugins: PluginWidget[] = [
  {
    id: "timeline",
    label: "Timeline",
    icon: "Activity",
    slot: "tab",
    order: 0,
    component: () => import("./timeline/TimelinePage"),
    sseEvents: ["tick", "message"],
    queryKeys: [["timeline"]],
  },
  {
    id: "repos",
    label: "Repos",
    icon: "GitBranch",
    slot: "tab",
    order: 10,
    component: () => import("../routes/repos") as any,
    sseEvents: ["tick"],
    queryKeys: [["repos"]],
  },
  {
    id: "dreams",
    label: "Dreams",
    icon: "Sparkles",
    slot: "tab",
    order: 20,
    component: () => import("../routes/dreams") as any,
    sseEvents: ["dream"],
    queryKeys: [["dreams"]],
  },
  {
    id: "tasks",
    label: "Tasks",
    icon: "CheckSquare",
    slot: "tab",
    order: 30,
    component: () => import("../routes/tasks") as any,
    sseEvents: ["tick"],
    queryKeys: [["tasks"]],
    featureGate: "VIGIL_TASKS",
  },
  {
    id: "actions",
    label: "Actions",
    icon: "Zap",
    slot: "tab",
    order: 40,
    component: () => import("../routes/actions") as any,
    sseEvents: ["action_pending", "action"],
    queryKeys: [["actions"]],
  },
  {
    id: "memory",
    label: "Memory",
    icon: "Brain",
    slot: "tab",
    order: 50,
    component: () => import("../routes/memory") as any,
    sseEvents: ["dream"],
    queryKeys: [["memory"]],
  },
  {
    id: "metrics",
    label: "Metrics",
    icon: "BarChart3",
    slot: "tab",
    order: 60,
    component: () => import("../routes/metrics") as any,
    sseEvents: ["tick", "decision"],
    queryKeys: [["metrics"]],
  },
  {
    id: "scheduler",
    label: "Scheduler",
    icon: "Clock",
    slot: "tab",
    order: 70,
    component: () => import("../routes/scheduler") as any,
    sseEvents: ["tick", "schedule_fired"],
    queryKeys: [["scheduler"]],
    featureGate: "VIGIL_SCHEDULER",
  },
  {
    id: "config",
    label: "Config",
    icon: "Settings",
    slot: "tab",
    order: 75,
    component: () => import("../routes/config") as any,
    sseEvents: ["config_changed"],
    queryKeys: [["config"]],
  },
  {
    id: "agents",
    label: "Agents",
    icon: "Bot",
    slot: "tab",
    order: 80,
    component: () => import("../routes/agents") as any,
    queryKeys: [["agents"]],
    featureGate: "VIGIL_AGENT_IDENTITY",
  },
  {
    id: "health",
    label: "Health",
    icon: "HeartPulse",
    slot: "tab",
    order: 85,
    component: () => import("../routes/health") as any,
    sseEvents: ["health"],
    queryKeys: [["health"]],
  },
  {
    id: "webhooks",
    label: "Webhooks",
    icon: "Webhook",
    slot: "tab",
    order: 90,
    component: () => import("../routes/webhooks") as any,
    sseEvents: ["webhook"],
    queryKeys: [["webhooks"]],
    featureGate: "VIGIL_WEBHOOKS",
  },
  {
    id: "channels",
    label: "Channels",
    icon: "Radio",
    slot: "tab",
    order: 91,
    component: () => import("../routes/channels") as any,
    sseEvents: ["channel"],
    queryKeys: [["channels"]],
    featureGate: "VIGIL_CHANNELS",
  },
  {
    id: "notifications",
    label: "Notifications",
    icon: "Bell",
    slot: "tab",
    order: 92,
    component: () => import("../routes/notifications") as any,
    sseEvents: ["message"],
    queryKeys: [["notifications"]],
    featureGate: "VIGIL_PUSH",
  },
  {
    id: "a2a",
    label: "A2A",
    icon: "Network",
    slot: "tab",
    order: 93,
    component: () => import("../routes/a2a") as any,
    queryKeys: [["a2a"]],
    featureGate: "VIGIL_A2A",
  },
];
