import type { PluginWidget } from "../types/plugin";

/**
 * Stub loader for plugins not yet ported to the plugin component contract.
 * Route modules export `Route` (TanStack Router convention), not a default
 * component matching WidgetProps. These stubs will be replaced as each
 * plugin is ported in future phases.
 */
const stub = (loader: () => Promise<any>) => loader as PluginWidget["component"];

export const corePlugins: PluginWidget[] = [
  {
    id: "timeline",
    label: "Timeline",
    icon: "Activity",
    slot: "tab",
    order: 0,
    component: () => import("./timeline/TimelinePage"),
    sseEvents: ["tick", "message"],
    queryKeys: [["timeline"]],
  },
  {
    id: "repos",
    label: "Repos",
    icon: "GitBranch",
    slot: "tab",
    order: 10,
    component: () => import("./repos/ReposPage"),
    sseEvents: ["tick"],
    queryKeys: [["repos"]],
  },
  {
    id: "dreams",
    label: "Dreams",
    icon: "Sparkles",
    slot: "tab",
    order: 20,
    component: () => import("./dreams/DreamsPage"),
    sseEvents: ["dream"],
    queryKeys: [["dreams"]],
  },
  {
    id: "tasks",
    label: "Tasks",
    icon: "CheckSquare",
    slot: "tab",
    order: 30,
    component: () => import("./tasks/TasksPage"),
    sseEvents: ["tick"],
    queryKeys: [["tasks"]],
    featureGate: "VIGIL_TASKS",
  },
  {
    id: "actions",
    label: "Actions",
    icon: "Zap",
    slot: "tab",
    order: 40,
    component: () => import("./actions/ActionsPage"),
    sseEvents: ["action_pending", "action"],
    queryKeys: [["actions"]],
  },
  {
    id: "memory",
    label: "Memory",
    icon: "Brain",
    slot: "tab",
    order: 50,
    component: () => import("./memory/MemoryPage"),
    sseEvents: ["dream"],
    queryKeys: [["memory"]],
  },
  {
    id: "metrics",
    label: "Metrics",
    icon: "BarChart3",
    slot: "tab",
    order: 60,
    component: () => import("./metrics/MetricsPage"),
    sseEvents: ["tick", "decision"],
    queryKeys: [["metrics"]],
  },
  {
    id: "scheduler",
    label: "Scheduler",
    icon: "Clock",
    slot: "tab",
    order: 70,
    component: () => import("./scheduler/SchedulerPage"),
    sseEvents: ["tick", "schedule_fired"],
    queryKeys: [["scheduler"]],
    featureGate: "VIGIL_SCHEDULER",
  },
  {
    id: "config",
    label: "Config",
    icon: "Settings",
    slot: "tab",
    order: 75,
    component: stub(() => import("../routes/config")),
    sseEvents: ["config_changed"],
    queryKeys: [["config"]],
  },
  {
    id: "agents",
    label: "Agents",
    icon: "Bot",
    slot: "tab",
    order: 80,
    component: stub(() => import("../routes/agents")),
    queryKeys: [["agents"]],
    featureGate: "VIGIL_AGENT_IDENTITY",
  },
  {
    id: "health",
    label: "Health",
    icon: "HeartPulse",
    slot: "tab",
    order: 85,
    component: stub(() => import("../routes/health")),
    sseEvents: ["health"],
    queryKeys: [["health"]],
  },
  {
    id: "webhooks",
    label: "Webhooks",
    icon: "Webhook",
    slot: "tab",
    order: 90,
    component: stub(() => import("../routes/webhooks")),
    sseEvents: ["webhook"],
    queryKeys: [["webhooks"]],
    featureGate: "VIGIL_WEBHOOKS",
  },
  {
    id: "channels",
    label: "Channels",
    icon: "Radio",
    slot: "tab",
    order: 91,
    component: stub(() => import("../routes/channels")),
    sseEvents: ["channel"],
    queryKeys: [["channels"]],
    featureGate: "VIGIL_CHANNELS",
  },
  {
    id: "notifications",
    label: "Notifications",
    icon: "Bell",
    slot: "tab",
    order: 92,
    component: stub(() => import("../routes/notifications")),
    sseEvents: ["message"],
    queryKeys: [["notifications"]],
    featureGate: "VIGIL_PUSH",
  },
  {
    id: "a2a",
    label: "A2A",
    icon: "Network",
    slot: "tab",
    order: 93,
    component: stub(() => import("../routes/a2a")),
    queryKeys: [["a2a"]],
    featureGate: "VIGIL_A2A",
  },
];
