import type { PluginWidget } from "../types/plugin";

export const corePlugins: PluginWidget[] = [
  {
    id: "timeline",
    label: "Timeline",
    icon: "Clock",
    slot: "tab",
    order: 1,
    component: () => import("../routes/index"),
  },
  {
    id: "repos",
    label: "Repos",
    icon: "GitBranch",
    slot: "tab",
    order: 2,
    component: () => import("../routes/repos"),
  },
  {
    id: "dreams",
    label: "Dreams",
    icon: "Sparkles",
    slot: "tab",
    order: 3,
    component: () => import("../routes/dreams"),
  },
  {
    id: "tasks",
    label: "Tasks",
    icon: "CheckSquare",
    slot: "tab",
    order: 4,
    component: () => import("../routes/tasks"),
  },
  {
    id: "actions",
    label: "Actions",
    icon: "Zap",
    slot: "tab",
    order: 5,
    component: () => import("../routes/actions"),
  },
  {
    id: "memory",
    label: "Memory",
    icon: "Brain",
    slot: "tab",
    order: 6,
    component: () => import("../routes/memory"),
  },
  {
    id: "metrics",
    label: "Metrics",
    icon: "BarChart3",
    slot: "tab",
    order: 7,
    component: () => import("../routes/metrics"),
  },
  {
    id: "scheduler",
    label: "Scheduler",
    icon: "Calendar",
    slot: "tab",
    order: 8,
    component: () => import("../routes/scheduler"),
  },
  {
    id: "config",
    label: "Config",
    icon: "Settings",
    slot: "tab",
    order: 9,
    component: () => import("../routes/config"),
  },
];
