/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DreamsRouteImport } from './routes/dreams'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as A2aRouteImport } from './routes/a2a'
import { Route as IndexRouteImport } from './routes/index'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamsRoute = DreamsRouteImport.update({
  id: '/dreams',
  path: '/dreams',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const A2aRoute = A2aRouteImport.update({
  id: '/a2a',
  path: '/a2a',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a2a': typeof A2aRoute
  '/actions': typeof ActionsRoute
  '/agents': typeof AgentsRoute
  '/channels': typeof ChannelsRoute
  '/config': typeof ConfigRoute
  '/dreams': typeof DreamsRoute
  '/health': typeof HealthRoute
  '/memory': typeof MemoryRoute
  '/metrics': typeof MetricsRoute
  '/notifications': typeof NotificationsRoute
  '/repos': typeof ReposRoute
  '/scheduler': typeof SchedulerRoute
  '/tasks': typeof TasksRoute
  '/webhooks': typeof WebhooksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a2a': typeof A2aRoute
  '/actions': typeof ActionsRoute
  '/agents': typeof AgentsRoute
  '/channels': typeof ChannelsRoute
  '/config': typeof ConfigRoute
  '/dreams': typeof DreamsRoute
  '/health': typeof HealthRoute
  '/memory': typeof MemoryRoute
  '/metrics': typeof MetricsRoute
  '/notifications': typeof NotificationsRoute
  '/repos': typeof ReposRoute
  '/scheduler': typeof SchedulerRoute
  '/tasks': typeof TasksRoute
  '/webhooks': typeof WebhooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a2a': typeof A2aRoute
  '/actions': typeof ActionsRoute
  '/agents': typeof AgentsRoute
  '/channels': typeof ChannelsRoute
  '/config': typeof ConfigRoute
  '/dreams': typeof DreamsRoute
  '/health': typeof HealthRoute
  '/memory': typeof MemoryRoute
  '/metrics': typeof MetricsRoute
  '/notifications': typeof NotificationsRoute
  '/repos': typeof ReposRoute
  '/scheduler': typeof SchedulerRoute
  '/tasks': typeof TasksRoute
  '/webhooks': typeof WebhooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a2a'
    | '/actions'
    | '/agents'
    | '/channels'
    | '/config'
    | '/dreams'
    | '/health'
    | '/memory'
    | '/metrics'
    | '/notifications'
    | '/repos'
    | '/scheduler'
    | '/tasks'
    | '/webhooks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a2a'
    | '/actions'
    | '/agents'
    | '/channels'
    | '/config'
    | '/dreams'
    | '/health'
    | '/memory'
    | '/metrics'
    | '/notifications'
    | '/repos'
    | '/scheduler'
    | '/tasks'
    | '/webhooks'
  id:
    | '__root__'
    | '/'
    | '/a2a'
    | '/actions'
    | '/agents'
    | '/channels'
    | '/config'
    | '/dreams'
    | '/health'
    | '/memory'
    | '/metrics'
    | '/notifications'
    | '/repos'
    | '/scheduler'
    | '/tasks'
    | '/webhooks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  A2aRoute: typeof A2aRoute
  ActionsRoute: typeof ActionsRoute
  AgentsRoute: typeof AgentsRoute
  ChannelsRoute: typeof ChannelsRoute
  ConfigRoute: typeof ConfigRoute
  DreamsRoute: typeof DreamsRoute
  HealthRoute: typeof HealthRoute
  MemoryRoute: typeof MemoryRoute
  MetricsRoute: typeof MetricsRoute
  NotificationsRoute: typeof NotificationsRoute
  ReposRoute: typeof ReposRoute
  SchedulerRoute: typeof SchedulerRoute
  TasksRoute: typeof TasksRoute
  WebhooksRoute: typeof WebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dreams': {
      id: '/dreams'
      path: '/dreams'
      fullPath: '/dreams'
      preLoaderRoute: typeof DreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a2a': {
      id: '/a2a'
      path: '/a2a'
      fullPath: '/a2a'
      preLoaderRoute: typeof A2aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  A2aRoute: A2aRoute,
  ActionsRoute: ActionsRoute,
  AgentsRoute: AgentsRoute,
  ChannelsRoute: ChannelsRoute,
  ConfigRoute: ConfigRoute,
  DreamsRoute: DreamsRoute,
  HealthRoute: HealthRoute,
  MemoryRoute: MemoryRoute,
  MetricsRoute: MetricsRoute,
  NotificationsRoute: NotificationsRoute,
  ReposRoute: ReposRoute,
  SchedulerRoute: SchedulerRoute,
  TasksRoute: TasksRoute,
  WebhooksRoute: WebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
